import Head from 'next/head'
import Layout from '../components/layout/main'
import {
    Container, Table, Button,
    Thead,
    Tbody,
    Tr,
    Th,
    Td,
    TableCaption,
    TableContainer,
} from '@chakra-ui/react'
import { FaTrash, FaEdit } from 'react-icons/fa'

interface StaticProps {
    value?: string,
    value2?: string,
    value3?: string
}

export default function Home(props) {

    return (
        <Container>
            <Head>
                <title>Book Store</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/bookstore.png" />
            </Head>
            <Layout heading='Book Store' />

            <TableContainer mt={10}>
                <Table size={'md'} colorScheme='teal'>
                    <TableCaption>List of Books</TableCaption>
                    <Thead>
                        <Tr>
                            <Th color={'white'} textAlign={'center'}>one</Th>
                            <Th color={'white'} textAlign={'center'}>two</Th>
                            <Th color={'white'} textAlign={'center'}>three</Th>
                            <Th color={'white'} textAlign={'center'}>Edit</Th>
                            <Th color={'white'} textAlign={'center'}>Delete</Th>
                        </Tr>
                    </Thead>
                    <Tbody>
                        {props.booksList.map((item: any) => (
                            <Tr>
                                <Td textAlign={'center'}>
                                    {item.value}
                                </Td >
                                <Td textAlign={'center'}>
                                    {item.value2}
                                </Td>
                                <Td textAlign={'center'}>
                                    {item.value3}
                                </Td>
                                <Td textAlign='center'><Button colorScheme={'teal'}><FaEdit /></Button></Td>
                                <Td textAlign='center'><Button >
                                    <FaTrash />
                                </Button></Td>
                            </Tr>
                        ))}
                    </Tbody>
                </Table>

            </TableContainer>
        </Container>
    )
}


let bookslist: StaticProps[] = [
    {
        value: "fine",
        value2: "by",
        value3: "me"
    },
    {
        value: "done",
        value2: "for",
        value3: "me"
    },
    {
        value: "gone",
        value2: "by",
        value3: "me"
    }

]

export async function getStaticProps() {
    return {
        props: {
            booksList: bookslist
        }
    }
}
