import Head from 'next/head'
import Layout from '../components/layout/main'
import {
    Container, Table, Button,
    Thead,
    Tbody,
    Tr,
    Th,
    Td,
    TableCaption,
    TableContainer,
} from '@chakra-ui/react'
import { FaTrash, FaEdit } from 'react-icons/fa'
import { useEffect, useState } from 'react'

export default function Home() {

    interface bookDetails {
        bookName: string
        author: string
        publisherName: string
        pricing?: number
        ratings?: number
    }

    const [booksList, setBooksList] = useState<[]>([])
    useEffect(() => {
        (async (): Promise<Array<bookDetails>> => {
            const response = await fetch("http://localhost:5005/book/get")
            const result = await response.json()
            setBooksList(result)
            return result
        })()

    }, [])

    return (
        <Container maxW={'900px'}>
            <Head>
                <title>Book Store</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/bookstore.png" />
            </Head>
            <Layout heading='Book Store' />

            <TableContainer mt={10}>
                <Table size={'sm'} colorScheme='teal'>
                    <TableCaption>List of Books</TableCaption>
                    <Thead>
                        <Tr>
                            <Th color={'white'} textAlign={'center'}>Book Name</Th>
                            <Th color={'white'} textAlign={'center'}>Author Name</Th>
                            <Th color={'white'} textAlign={'center'}>Publisher Name</Th>
                            <Th color={'white'} textAlign={'center'}>Pricing</Th>
                            <Th color={'white'} textAlign={'center'}>Ratings</Th>
                            <Th color={'white'} textAlign={'center'}>Edit</Th>
                            <Th color={'white'} textAlign={'center'}>Delete</Th>
                        </Tr>
                    </Thead>
                    <Tbody>
                        {booksList.map((item: any) => (
                            <Tr>
                                <Td key={item.BookName} textAlign={'center'}>
                                    {item.bookName}
                                </Td >
                                <Td key={item.authName} textAlign={'center'}>
                                    {item.author}
                                </Td>
                                <Td key={item.publisherName} textAlign={'center'}>
                                    {item.publisherName}
                                </Td>
                                <Td>{item.pricing}</Td>
                                <Td>{item.ratings}</Td>
                                <Td textAlign='center'><Button colorScheme={'teal'}><FaEdit /></Button></Td>
                                <Td textAlign='center'><Button >
                                    <FaTrash />
                                </Button></Td>
                            </Tr>
                        ))}
                    </Tbody>
                </Table>
            </TableContainer>
        </Container>
    )
}
